# theme = "catppuccin_latte"
theme = "catppuccin_mocha"


[editor]
line-number = "relative"
mouse = false

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
# enable = true
# wrap-at-text-width = true
