# theme = "catppuccin_latte"
theme = "catppuccin_mocha"


[editor]
bufferline = "multiple"
line-number = "relative"
# mouse = false

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.file-picker]
hidden = false

# [editor.soft-wrap]
# enable = true
# wrap-at-text-width = true

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
# C-y = [ ':sh rm -f /tmp/yazi-path', ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-path', ":open %sh{/bin/cat /tmp/yazi-path}", ":redraw" ]
