[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
